import Header from './components/Header'
import './globals.css'
import { ContextProvider } from './components/Clients'

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ContextProvider>
          <>
          <Header />
          {children}
          </>
        </ContextProvider>
      </body>
    </html>
  )
}
